[workspace]
resolver = "3"
members = ["crates/lsp", "crates/lsp-py"]
package.version = "0.0.0"

[workspace.dependencies]
beancount-core = { git = "https://github.com/trim21/beancount.git", rev = "079bd1db77e09ad030329c6ec30744ed42a938d3" }
beancount-parser = { git = "https://github.com/trim21/beancount.git", rev = "079bd1db77e09ad030329c6ec30744ed42a938d3" }
chumsky = "0.13.0"
ropey = "1.6.1"
tokio = { version = "1.53.1", features = ["fs", "io-std", "macros", "rt-multi-thread", "sync"] }
tower-lsp-server = "0.23.0"

[patch.crates-io]
