version: '3'

tasks:
  build:lsp:
    desc: Build Rust LSP crate
    cmds:
      - cargo build -p beancount-lsp --release

  test:
    desc: Test Rust LSP crate
    cmds:
      - cargo nextest run -p beancount-lsp

  build:lsp-py:
    desc: Build Python extension via maturin (uses project-local uv env)
    cmds:
      - uv build --wheel .

  test:lsp-py:
    desc: (Placeholder) Python package has no tests; runs cargo checks for the pyo3 crate
    cmds:
      - cargo test -p beancount-lsp-py

  build:vscode:
    desc: (Placeholder) Python package has no tests; runs cargo checks for the pyo3 crate
    cmds:
      - pnpm run -C vscode build

  bump:vscode:
    vars:
      VERSION:
        sh: jq -r '.version' vscode/package.json
    cmds:
      - git add vscode/package.json
      - 'git commit -m "release(vscode): {{.VERSION}}"'
      - 'git tag "vscode/v{{.VERSION}}" -m "vscode/v{{.VERSION}}" -a'

  bump:lsp:
    vars:
      VERSION:
        sh: yq -r '.project.version' pyproject.toml
    cmds:
      - git add pyproject.toml
      - 'git commit -m "release: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}" -a'
